# Generated by Django 3.2.5 on 2021-07-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='workspace_id',
            new_name='channel_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='slackuser',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slackuser',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slackuser',
            name='user_id',
            field=models.TextField(unique=True),
        ),
    ]
