# Generated by Django 3.2.5 on 2021-07-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_client_message_id_message_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackuser',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
