# Generated by Django 3.2.5 on 2021-07-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_slackuser_is_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
