# Generated by Django 3.2.5 on 2021-07-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_channel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlackUser',
            new_name='User',
        ),
    ]
